{"name": "Попытка залогина без логина или пароля завершается ошибкой", "status": "passed", "steps": [{"name": "Получаем пару логин-пароль существующего курьера", "status": "passed", "parameters": [{"name": "exclude_login", "value": "True"}, {"name": "exclude_password", "value": "False"}, {"name": "corrupt_password", "value": "False"}], "start": 1704987239599, "stop": 1704987239599}, {"name": "Залогин курьера [POST]", "status": "passed", "parameters": [{"name": "credentials", "value": "{'password': 'password-test-777'}"}], "start": 1704987239599, "stop": 1704987239758}, {"name": "Проверяем код ответа сервера", "status": "passed", "parameters": [{"name": "response", "value": "<Response [400]>"}, {"name": "code", "value": "400"}], "start": 1704987239758, "stop": 1704987239758}], "parameters": [{"name": "exclude_login", "value": "True"}, {"name": "exclude_password", "value": "False"}], "start": 1704987239599, "stop": 1704987239759, "uuid": "8c07a0f0-0878-46b8-a181-8f78f35c134f", "historyId": "8159e0b21b13536bb5bfe2432def6139", "testCaseId": "b917bdfb7e18c40fc5d7c91d7db008bc", "fullName": "tests.test_login_courier.TestLoginCourier#test_auth_without_one_credential_returns_error_status_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "i111355119"}, {"name": "thread", "value": "60430-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}